create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view', 'product_view', 'product_click', 'add_to_cart', 'checkout_started')),
  visitor_hash text not null,
  session_id text not null,
  path text not null default '/',
  product_id text,
  product_name text,
  referrer_host text,
  created_at timestamptz not null default now()
);

create index if not exists site_events_created_idx on public.site_events (created_at desc);
create index if not exists site_events_name_created_idx on public.site_events (event_name, created_at desc);
create index if not exists site_events_product_created_idx on public.site_events (product_id, created_at desc) where product_id is not null;
create index if not exists site_events_visitor_created_idx on public.site_events (visitor_hash, created_at desc);

alter table public.site_events enable row level security;

comment on table public.site_events is 'Consent-based, first-party site analytics. Visitor identifiers are hashed before storage; IP addresses are not stored.';
